name: github-actions-saludo
run-name: {{ github.actors }} is Guthub actions
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hola mundo desde un workflow