name: github-actions-saludo

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hola mundo desde un workflow
